deploy/build.yaml: don't fail if fetch --unshallow does
Sometimes the build step that runs `git fetch --unshallow` fails
because the repo is already complete. (It's unclear why this happens;
perhaps the build step is run twice?)

Make the step idempotent by doing nothing if the command fails.

Change-Id: I28093a6f24a5e172b4dd7c7eed91aa69ffed9ab5
Reviewed-on: https://go-review.googlesource.com/c/vulndb/+/434617
Reviewed-by: Tatiana Bradley <tatiana@golang.org>
Run-TryBot: Jonathan Amsterdam <jba@google.com>
TryBot-Result: Gopher Robot <gobot@golang.org>

diff --git a/deploy/build.yaml b/deploy/build.yaml
--- a/deploy/build.yaml
+++ b/deploy/build.yaml
@@ -14,7 +14,13 @@ steps:
 
   - id: Unshallow
     name: gcr.io/cloud-builders/git
-    args: ["fetch", "--unshallow"]
+    entrypoint: bash
+    args:
+      - -c
+      - |
+        if ! git fetch --unshallow; then
+          echo "git fetch --unshallow failed, no worries mate"
+        fi
 
   - id: Generate
     name: golang
